# Loops

In [1]:
for i in range(10):
  print(i, end=' ')

0 1 2 3 4 5 6 7 8 9 

In [2]:
for i in range(5,10):
  print(i, end=' ')

5 6 7 8 9 

In [3]:
for i in range(5,20,2):
  print(i, end=' ')

5 7 9 11 13 15 17 19 

In [4]:
L =  [10,20,30,40,50]
for i in L:
  print(i, end=' ')

10 20 30 40 50 

In [5]:
L =  [10,20,30,40,50]
for i in range(len(L)):
  print(L[i], end=' ')

10 20 30 40 50 

In [6]:
L =  [10,20,30,40,50]
for i, item in enumerate(L):
  print(i,item, end = '    ')

0 10    1 20    2 30    3 40    4 50    

# Functions

In [7]:
def my_function(a=5, b=10):
  print('a =',a,'  b =',b)

In [8]:
my_function()

a = 5   b = 10


In [9]:
my_function(a=50)

a = 50   b = 10


In [10]:
my_function(b=50)

a = 5   b = 50


In [11]:
my_function(50,100)

a = 50   b = 100


# Objects and classes

In [12]:
class My_class:

    def __init__(self, x=10, y=20):
        # a and b are the attributes of the object
        w = x*y      # w is a local varible in the initializer, it will be destroyed after execution
        self.a = x
        self.b = w

    # define a static method - to call it we do: My_class.my_static_method()
    def my_static_method():
        print('Running static method')
        # self is undefined in static methods

    # define a non-static method - to call it we do: object_name.my_non_static_method()
    # then self takes the value of object_name
    def my_non_static_method(self):
        print('Running non-static method')
        print('the object address is',self)
        print('the attribute values are: a =', self.a,'b =', self.b)

    def f(self, x, y): # if we call obj.f(10,20), then self = obj, x = 10, y = 20
        print(self, x, y)

In [13]:
My_class.my_static_method()

Running static method


In [14]:
obj_1 = My_class(5)
obj_1.my_non_static_method()

Running non-static method
the object address is <__main__.My_class object at 0x11057e7c0>
the attribute values are: a = 5 b = 100


In [15]:
print('the object address is',obj_1)
print('the attribute values are: a =',obj_1.a,'b =', obj_1.b)

the object address is <__main__.My_class object at 0x11057e7c0>
the attribute values are: a = 5 b = 100


In [16]:
obj_1.f(10,20)

<__main__.My_class object at 0x11057e7c0> 10 20


# Lists

In [17]:
L = [10,20,30,40,50]
print(L)

[10, 20, 30, 40, 50]


In [18]:
print(len(L))

5


In [19]:
L.append(100)
print(L)

[10, 20, 30, 40, 50, 100]


In [20]:
L = L + [7,2,9,12]
print(L)

[10, 20, 30, 40, 50, 100, 7, 2, 9, 12]


In [21]:
print(L[2])

30


In [22]:
print(L[-2])

9


In [23]:
print(L[3:])

[40, 50, 100, 7, 2, 9, 12]


In [24]:
print(L[3:8])

[40, 50, 100, 7, 2]


In [25]:
print(L[1:6:2])

[20, 40, 100]


In [26]:
print(L[:8])

[10, 20, 30, 40, 50, 100, 7, 2]


In [27]:
print(L[::2])

[10, 30, 50, 7, 9]


In [28]:
L = [i**2 for i in range(5)]
print(L)

[0, 1, 4, 9, 16]


In [29]:
L = [i**2 for i in range(5) if i%2==0]
print(L)

[0, 4, 16]


# Arrays

In [30]:
import numpy as np

In [31]:
L = [i**2 for i in range(12)]
A =np.array(L)
print(A)

[  0   1   4   9  16  25  36  49  64  81 100 121]


In [32]:
print(A.shape)

(12,)


In [33]:
print(A[3])

9


In [34]:
print(A[:3])

[0 1 4]


In [35]:
print(A[3:])

[  9  16  25  36  49  64  81 100 121]


In [36]:
print(A[3:7])

[ 9 16 25 36]


In [37]:
B = A.reshape(3,4)
print(B)

[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]


In [38]:
print(B.shape)

(3, 4)


In [39]:
print(B[1,2])

36


In [40]:
print(B[1,:])

[16 25 36 49]


In [41]:
print(B[:,1])

[ 1 25 81]


In [42]:
C = A%19
print(C)

[ 0  1  4  9 16  6 17 11  7  5  5  7]


In [43]:
print(np.sum(C))

88


In [44]:
print(np.max(C))

17


In [45]:
print(np.argmax(C))

6


# Sets

In [46]:
S = set([4,1,8,9,2])
print(S)

{1, 2, 4, 8, 9}


In [47]:
for s in S:
  print(s,end=' ')

1 2 4 8 9 

In [48]:
S = set()
for i in range(2,20,3):
  S.add(i)
  print(S)

{2}
{2, 5}
{8, 2, 5}
{8, 2, 11, 5}
{2, 5, 8, 11, 14}
{2, 5, 8, 11, 14, 17}


In [49]:
print(S)
S.remove(11)
print(S)

{2, 5, 8, 11, 14, 17}
{2, 5, 8, 14, 17}


In [50]:
S.discard(8)
print(S)

{2, 5, 14, 17}


In [51]:
S.discard(88)
print(S)

{2, 5, 14, 17}


In [52]:
print(14 in S)

True


In [53]:
print(14 not in S)

False


In [54]:
print(not 14 in S)

False


In [55]:
print(11 in S)

False


In [56]:
T = set([2, 7,14,21])

In [57]:
print(S.union(T))

{2, 5, 7, 14, 17, 21}


In [58]:
print(S.intersection(T))

{2, 14}


In [59]:
print(S.difference(T))

{17, 5}


In [60]:
print(T.difference(S))

{21, 7}


In [61]:
S = {i**2 for i in range(6)}
print(S)

{0, 1, 4, 9, 16, 25}


# Dictionaries

In [62]:
D = {}
D[0] = 5
D['CS2302'] = 'Data Structures'
print(D)

{0: 5, 'CS2302': 'Data Structures'}


In [63]:
print(D[0])

5


In [64]:
print(D.get('CS2302'))

Data Structures


In [65]:
print(D.get('CS2401'))

None


In [66]:
print(D.get('CS2401',0))

0


In [67]:
D = {i:i**2 for i in range(10)}
print(D)

{0: 0, 1: 1, 2: 4, 3: 9, 4: 16, 5: 25, 6: 36, 7: 49, 8: 64, 9: 81}


In [68]:
print(D[5])

25
